travis:
  secure:
    BINSTAR_TOKEN: WzF4ICyKDq2AtPpOXWDgvYoVa0xGbYQ5a1fs4b2relCK0ZwK88+ovmAfC6Z35SUHaAbu8ZR/Tz+9ZfyHO8L6kh46qRxI462/Ljn1r/DwEM488PzUE0vz81BEsEvcVIWCEvISwiei1BFY789A9XTULA2kU+0X0FaIVzchHhPFFvCg86r5vC4XVpllhezRlo/wN03pFkZzA6FEDAKpSP8/miiyJIgxf7nrsud6F4Inu158YMOGvx2zULTZgu1K2g/fRdA+BrGdfjEmzD7EDhkhFPhfSSClZxEcdOetSBNwnYqOidzCUIjiiR78kOYU6vfDlCzoxypho6tc05hLEUae8S8E58keMGXwt5nwQYgiYpB7DELkzHA15+AVYGbq6IIDYRzwE/NKyeZs6jIDwU2+8eSuDmEsA8+kEfRJKG+Pyb29natoCo0ukZLb1wyy7icQHlTmmh5E7RqPkJ8s1kxdN6Appuh1eCaXzy2m323a0O2oHxh1J57CxWW7Ofi3LsV80heqMPau5ZVVqSQ6Jp+hgL/5PhDoT5wxCTsFii57sMnAU0gVZV/wesMYg4KXTE/yKd5S7yc8mJFgRbV4K+RwHYpJosum/WRqiiqpQWvyz8JAC1+nwfE34HQ7qD2gMDx2+IwwoF1sADsTy92+HU8kovmxYTC98MeNShF9D6JL/6I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
